;; -*- lexical-binding: t -*-

;; Some handy or popular color pallets

;; https://github.com/bbatsov/zenburn-emacs
(defconst palette/zenburn/bg+3      "#6F6F6F"  "Zenburn palette: #6F6F6F.")
(defconst palette/zenburn/bg+2      "#5F5F5F"  "Zenburn palette: #5F5F5F.")
(defconst palette/zenburn/bg+1      "#4F4F4F"  "Zenburn palette: #4F4F4F.")
(defconst palette/zenburn/bg+0      "#494949"  "Zenburn palette: #494949.")
(defconst palette/zenburn/bg        "#3F3F3F"  "Zenburn palette: #3F3F3F.")
(defconst palette/zenburn/bg-0      "#383838"  "Zenburn palette: #383838.")
(defconst palette/zenburn/bg-1      "#2B2B2B"  "Zenburn palette: #2B2B2B.")
(defconst palette/zenburn/bg-2      "#000000"  "Zenburn palette: #000000.")
(defconst palette/zenburn/blue+1    "#94BFF3"  "Zenburn palette: #94BFF3.")
(defconst palette/zenburn/blue      "#8CD0D3"  "Zenburn palette: #8CD0D3.")
(defconst palette/zenburn/blue-1    "#7CB8BB"  "Zenburn palette: #7CB8BB.")
(defconst palette/zenburn/blue-2    "#6CA0A3"  "Zenburn palette: #6CA0A3.")
(defconst palette/zenburn/blue-3    "#5C888B"  "Zenburn palette: #5C888B.")
(defconst palette/zenburn/blue-4    "#4C7073"  "Zenburn palette: #4C7073.")
(defconst palette/zenburn/blue-5    "#366060"  "Zenburn palette: #366060.")
(defconst palette/zenburn/cyan      "#93E0E3"  "Zenburn palette: #93E0E3.")
(defconst palette/zenburn/fg+1      "#FFFFEF"  "Zenburn palette: #FFFFEF.")
(defconst palette/zenburn/fg        "#DCDCCC"  "Zenburn palette: #DCDCCC.")
(defconst palette/zenburn/fg-1      "#656555"  "Zenburn palette: #656555.")
(defconst palette/zenburn/green+4   "#BFEBBF"  "Zenburn palette: #BFEBBF.")
(defconst palette/zenburn/green+3   "#AFD8AF"  "Zenburn palette: #AFD8AF.")
(defconst palette/zenburn/green+2   "#9FC59F"  "Zenburn palette: #9FC59F.")
(defconst palette/zenburn/green+1   "#8FB28F"  "Zenburn palette: #8FB28F.")
(defconst palette/zenburn/green     "#7F9F7F"  "Zenburn palette: #7F9F7F.")
(defconst palette/zenburn/green-1   "#5F7F5F"  "Zenburn palette: #5F7F5F.")
(defconst palette/zenburn/magenta   "#DC8CC3"  "Zenburn palette: #DC8CC3.")
(defconst palette/zenburn/orange    "#DFAF8F"  "Zenburn palette: #DFAF8F.")
(defconst palette/zenburn/red+1     "#DCA3A3"  "Zenburn palette: #DCA3A3.")
(defconst palette/zenburn/red       "#CC9393"  "Zenburn palette: #CC9393.")
(defconst palette/zenburn/red-1     "#BC8383"  "Zenburn palette: #BC8383.")
(defconst palette/zenburn/red-2     "#AC7373"  "Zenburn palette: #AC7373.")
(defconst palette/zenburn/red-3     "#9C6363"  "Zenburn palette: #9C6363.")
(defconst palette/zenburn/red-4     "#8C5353"  "Zenburn palette: #8C5353.")
(defconst palette/zenburn/yellow    "#F0DFAF"  "Zenburn palette: #F0DFAF.")
(defconst palette/zenburn/yellow-1  "#E0CF9F"  "Zenburn palette: #E0CF9F.")
(defconst palette/zenburn/yellow-2  "#D0BF8F"  "Zenburn palette: #D0BF8F.")


;; https://srcery-colors.github.io/
(defconst palette/srcery/black "#1C1B19")
(defconst palette/srcery/red "#EF2F27")
(defconst palette/srcery/green "#519F50")
(defconst palette/srcery/yellow "#FBB829")
(defconst palette/srcery/blue "#2C78BF")
(defconst palette/srcery/magenta "#E02C6D")
(defconst palette/srcery/cyan "#0AAEB3")
(defconst palette/srcery/white "#918175")
(defconst palette/srcery/bright-black "#2D2C29")
(defconst palette/srcery/bright-red "#F75341")
(defconst palette/srcery/bright-green "#98BC37")
(defconst palette/srcery/bright-yellow "#FED06E")
(defconst palette/srcery/bright-blue "#68A8E4")
(defconst palette/srcery/bright-magenta "#FF5C8F")
(defconst palette/srcery/bright-cyan "#53FDE9")
(defconst palette/srcery/bright-white "#FCE8C3")
(defconst palette/srcery/orange "#FF5F00")
(defconst palette/srcery/bright-orange "#FF8700")
(defconst palette/srcery/hard-black "#121212")
(defconst palette/srcery/gray-1 "#262626")
(defconst palette/srcery/gray-2 "#303030")
(defconst palette/srcery/gray-3 "#3A3A3A")
(defconst palette/srcery/gray-4 "#444444")
(defconst palette/srcery/gray-5 "#4E4E4E")
(defconst palette/srcery/dark-red "#5f0000")
(defconst palette/srcery/dark-green "#005f00")
(defconst palette/srcery/dark-cyan "#005f5f")
(defconst palette/srcery/dark-blue "#00005f")


;; doom-one https://github.com/hlissner/emacs-doom-themes
(defconst palette/doom-one/bg "#282c34")
(defconst palette/doom-one/bg-alt     "#21242b")
(defconst palette/doom-one/base0      "#1B2229")
(defconst palette/doom-one/base1      "#1c1f24")
(defconst palette/doom-one/base2      "#202328")
(defconst palette/doom-one/base3      "#23272e")
(defconst palette/doom-one/base4      "#3f444a")
(defconst palette/doom-one/base5      "#5B6268")
(defconst palette/doom-one/base6      "#73797e")
(defconst palette/doom-one/base7      "#9ca0a4")
(defconst palette/doom-one/base8      "#DFDFDF")
(defconst palette/doom-one/fg         "#bbc2cf")
(defconst palette/doom-one/fg-alt     "#5B6268")
(defconst palette/doom-one/grey       palette/doom-one/base4)
(defconst palette/doom-one/red        "#ff6c6b")
(defconst palette/doom-one/orange     "#da8548")
(defconst palette/doom-one/green      "#98be65")
(defconst palette/doom-one/teal       "#4db5bd")
(defconst palette/doom-one/yellow     "#ECBE7B")
(defconst palette/doom-one/blue       "#51afef")
(defconst palette/doom-one/dark-blue  "#2257A0")
(defconst palette/doom-one/magenta    "#c678dd")
(defconst palette/doom-one/violet     "#a9a1e1")
(defconst palette/doom-one/cyan       "#46D9FF")
(defconst palette/doom-one/dark-cyan  "#5699AF")

(defconst palette/doom-vibrant/bg         "#242730")
(defconst palette/doom-vibrant/fg         "#bbc2cf")
(defconst palette/doom-vibrant/bg-alt     "#2a2e38")
(defconst palette/doom-vibrant/fg-alt     "#5D656B")
(defconst palette/doom-vibrant/base0      "#1c1f24")
(defconst palette/doom-vibrant/base1      "#1c1f24")
(defconst palette/doom-vibrant/base2      "#21272d")
(defconst palette/doom-vibrant/base3      "#23272e")
(defconst palette/doom-vibrant/base4      "#484854")
(defconst palette/doom-vibrant/base5      "#62686E")
(defconst palette/doom-vibrant/base6      "#757B80")
(defconst palette/doom-vibrant/base7      "#9ca0a4")
(defconst palette/doom-vibrant/base8      "#DFDFDF")
(defconst palette/doom-vibrant/grey       palette/doom-vibrant/base4)
(defconst palette/doom-vibrant/red        "#ff665c")
(defconst palette/doom-vibrant/orange     "#e69055")
(defconst palette/doom-vibrant/green      "#7bc275")
(defconst palette/doom-vibrant/teal       "#4db5bd")
(defconst palette/doom-vibrant/yellow     "#FCCE7B")
(defconst palette/doom-vibrant/blue       "#51afef")
(defconst palette/doom-vibrant/dark-blue  "#1f5582")
(defconst palette/doom-vibrant/magenta    "#C57BDB")
(defconst palette/doom-vibrant/violet     "#a991f1")
(defconst palette/doom-vibrant/cyan       "#5cEfFF")
(defconst palette/doom-vibrant/dark-cyan  "#6A8FBF")


;; https://github.com/nashamri/spacemacs-theme
(defconst palette/spacemacs/act1          "#222226")
(defconst palette/spacemacs/act2          "#5d4d7a")
(defconst palette/spacemacs/base          "#b2b2b2")
(defconst palette/spacemacs/base-dim      "#686868")
(defconst palette/spacemacs/bg1           "#292b2e")
(defconst palette/spacemacs/bg2           "#212026")
(defconst palette/spacemacs/bg3           "#100a14")
(defconst palette/spacemacs/bg4           "#0a0814")
(defconst palette/spacemacs/border        "#5d4d7a")
(defconst palette/spacemacs/cblk          "#cbc1d5")
(defconst palette/spacemacs/cblk-bg       "#2f2b33")
(defconst palette/spacemacs/cblk-ln       "#827591")
(defconst palette/spacemacs/cblk-ln-bg    "#373040")
(defconst palette/spacemacs/cursor        "#e3dedd")
(defconst palette/spacemacs/const         "#a45bad")
(defconst palette/spacemacs/comment       "#2aa1ae")
(defconst palette/spacemacs/comment-light "#2aa1ae")
(defconst palette/spacemacs/comment-bg    "#292e34")
(defconst palette/spacemacs/comp          "#c56ec3")
(defconst palette/spacemacs/err           "#e0211d")
(defconst palette/spacemacs/func          "#bc6ec5")
(defconst palette/spacemacs/head1         "#4f97d7")
(defconst palette/spacemacs/head1-bg      "#293239")
(defconst palette/spacemacs/head2         "#2d9574")
(defconst palette/spacemacs/head2-bg      "#293235")
(defconst palette/spacemacs/head3         "#67b11d")
(defconst palette/spacemacs/head3-bg      "#293235")
(defconst palette/spacemacs/head4         "#b1951d")
(defconst palette/spacemacs/head4-bg      "#32322c")
(defconst palette/spacemacs/highlight     "#444155")
(defconst palette/spacemacs/highlight-dim "#3b314d")
(defconst palette/spacemacs/keyword       "#4f97d7")
(defconst palette/spacemacs/lnum          "#44505c")
(defconst palette/spacemacs/mat           "#86dc2f")
(defconst palette/spacemacs/meta          "#9f8766")
(defconst palette/spacemacs/str           "#2d9574")
(defconst palette/spacemacs/suc           "#86dc2f")
(defconst palette/spacemacs/ttip          "#9a9aba")
(defconst palette/spacemacs/ttip-sl       "#5e5079")
(defconst palette/spacemacs/ttip-bg       "#34323e")
(defconst palette/spacemacs/type          "#ce537a")
(defconst palette/spacemacs/var           "#7590db")
(defconst palette/spacemacs/war           "#dc752f")
;; colors
(defconst palette/spacemacs/aqua          "#2d9574")
(defconst palette/spacemacs/aqua-bg       "#293235")
(defconst palette/spacemacs/green         "#67b11d")
(defconst palette/spacemacs/green-bg      "#293235")
(defconst palette/spacemacs/green-bg-s    "#29422d")
(defconst palette/spacemacs/cyan          "#28def0")
(defconst palette/spacemacs/red           "#f2241f")
(defconst palette/spacemacs/red-bg        "#3c2a2c")
(defconst palette/spacemacs/red-bg-s      "#512e31")
(defconst palette/spacemacs/blue          "#4f97d7")
(defconst palette/spacemacs/blue-bg       "#293239")
(defconst palette/spacemacs/blue-bg-s     "#2d4252")
(defconst palette/spacemacs/magenta       "#a31db1")
(defconst palette/spacemacs/yellow        "#b1951d")
(defconst palette/spacemacs/yellow-bg     "#32322c")


;; https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el
(defconst palette/monokai/yellow "#E6DB74")
(defconst palette/monokai/orange "#FD971F")
(defconst palette/monokai/red "#F92672")
(defconst palette/monokai/magenta "#FD5FF0")
(defconst palette/monokai/blue "#66D9EF")
(defconst palette/monokai/green "#A6E22E")
(defconst palette/monokai/cyan "#A1EFE4")
(defconst palette/monokai/violet "#AE81FF")
(defconst palette/monokai/gray "#64645E")
(defconst palette/monokai/foreground "#F8F8F2")
(defconst palette/monokai/background "#272822")
(defconst palette/monokai/comments "#75715E")
(defconst palette/monokai/emphasis "#F8F8F0")
(defconst palette/monokai/line-number "#8F908A")
(defconst palette/monokai/highlight "#49483E")
(defconst palette/monokai/highlight-alt "#3E3D31")
(defconst palette/monokai/highlight-line "#3C3D37")
;; Functionality specific colors
(defconst palette/monokai/diff-blue-base      "#232438")
(defconst palette/monokai/diff-blue-emphasis  "#1F204E")
(defconst palette/monokai/diff-green-base     "#233E1E")
(defconst palette/monokai/diff-green-emphasis "#1F541A")
(defconst palette/monokai/diff-red-base       "#3D241E")
(defconst palette/monokai/diff-red-emphasis   "#53201A")
;; Darker and lighter accented colors
(defconst palette/monokai/yellow-d       "#BEB244")
(defconst palette/monokai/yellow-l       "#FFF7A8")
(defconst palette/monokai/orange-d       "#D47402")
(defconst palette/monokai/orange-l       "#FFAC4A")
(defconst palette/monokai/red-d          "#F70057")
(defconst palette/monokai/red-l          "#FA518D")
(defconst palette/monokai/magenta-d      "#FB35EA")
(defconst palette/monokai/magenta-l      "#FE8CF4")
(defconst palette/monokai/violet-d       "#945AFF")
(defconst palette/monokai/violet-l       "#C9ACFF")
(defconst palette/monokai/blue-d         "#40CAE4")
(defconst palette/monokai/blue-l         "#92E7F7")
(defconst palette/monokai/cyan-d         "#74DBCD")
(defconst palette/monokai/cyan-l         "#D3FBF6")
(defconst palette/monokai/green-d        "#86C30D")
(defconst palette/monokai/green-l        "#BBEF53")
(defconst palette/monokai/gray-d         "#35331D")
(defconst palette/monokai/gray-l         "#7B7962")
;; Adaptive higher/lower contrast accented colors
(defconst palette/monokai/foreground-hc  "#141414")
(defconst palette/monokai/foreground-lc  "#171A0B")
;; High contrast colors
(defconst palette/monokai/yellow-hc      "#FFFACE")
(defconst palette/monokai/yellow-lc      "#9A8F21")
(defconst palette/monokai/orange-hc      "#FFBE74")
(defconst palette/monokai/orange-lc      "#A75B00")
(defconst palette/monokai/red-hc         "#FEB0CC")
(defconst palette/monokai/red-lc         "#F20055")
(defconst palette/monokai/magenta-hc     "#FEC6F9")
(defconst palette/monokai/magenta-lc     "#F309DF")
(defconst palette/monokai/violet-hc      "#F0E7FF")
(defconst palette/monokai/violet-lc      "#7830FC")
(defconst palette/monokai/blue-hc        "#CAF5FD")
(defconst palette/monokai/blue-lc        "#1DB4D0")
(defconst palette/monokai/cyan-hc        "#D3FBF6")
(defconst palette/monokai/cyan-lc        "#4BBEAE")
(defconst palette/monokai/green-hc       "#CCF47C")
(defconst palette/monokai/green-lc       "#679A01")


;;https://github.com/purcell/color-theme-sanityinc-tomorrow/
(defconst palette/tomorrow-night/background "#1d1f21")
(defconst palette/tomorrow-night/alt-background "#22a224a427a7")
(defconst palette/tomorrow-night/current-line "#282a2e")
(defconst palette/tomorrow-night/selection "#373b41")
(defconst palette/tomorrow-night/foreground "#c5c8c6")
(defconst palette/tomorrow-night/comment "#969896")
(defconst palette/tomorrow-night/red "#cc6666")
(defconst palette/tomorrow-night/orange "#de935f")
(defconst palette/tomorrow-night/yellow "#f0c674")
(defconst palette/tomorrow-night/green "#b5bd68")
(defconst palette/tomorrow-night/aqua "#8abeb7")
(defconst palette/tomorrow-night/blue "#81a2be")
(defconst palette/tomorrow-night/purple "#b294bb")

;; https://ethanschoonover.com/solarized/
(defconst palette/solarized-dark/base03 "#002b36")
(defconst palette/solarized-dark/base02 "#073642")
(defconst palette/solarized-dark/base01 "#586e75")
(defconst palette/solarized-dark/base00 "#657b83")
(defconst palette/solarized-dark/base0  "#839496")
(defconst palette/solarized-dark/base1  "#93a1a1")
(defconst palette/solarized-dark/base2  "#eee8d5")
(defconst palette/solarized-dark/base3  "#fdf6e3")
(defconst palette/solarized-dark/yellow "#b58900")
(defconst palette/solarized-dark/orange "#cb4b16")
(defconst palette/solarized-dark/red    "#dc322f")
(defconst palette/solarized-dark/magenta"#d33682")
(defconst palette/solarized-dark/violet "#6c71c4")
(defconst palette/solarized-dark/blue   "#268bd2")
(defconst palette/solarized-dark/cyan   "#2aa198")
(defconst palette/solarized-dark/green  "#859900")


;; https://github.com/morhetz/gruvbox
(defconst palette/gruvbox/bg-hard "#1d2021")  ; bg0_h
(defconst palette/gruvbox/bg-soft  "#32302f") ; bg0_s
(defconst palette/gruvbox/bg-medium "#282828") ; bg0
(defconst palette/gruvbox/bg-alt-hard "#0d1011") ; (self-defined)
(defconst palette/gruvbox/bg-alt-soft "#282828") ; bg0
(defconst palette/gruvbox/bg-alt-medium "#1d2021") ; bg_h
(defconst palette/gruvbox/bg-alt2 "#504945") ; bg2 (for region, selection etc.)

(defconst palette/gruvbox/base0      "#0d1011") ; (self-defined)
(defconst palette/gruvbox/base1      "#1d2021") ; bg0_h
(defconst palette/gruvbox/base2      "#282828") ; bg0
(defconst palette/gruvbox/base3      "#3c3836") ; bg1
(defconst palette/gruvbox/base4      "#665c54") ; bg3
(defconst palette/gruvbox/base5      "#7c6f64") ; bg4
(defconst palette/gruvbox/base6      "#928374") ; gray
(defconst palette/gruvbox/base7      "#d5c4a1") ; fg2
(defconst palette/gruvbox/base8      "#fbf1c7") ; fg0
(defconst palette/gruvbox/fg         "#ebdbb2") ; fg/fg1
(defconst palette/gruvbox/fg-alt     "#d5c4a1") ; fg2
;; Standardized official colours from gruvbox
(defconst palette/gruvbox/grey        "#928374") ; gray
(defconst palette/gruvbox/red         "#fb4934") ; bright-red
(defconst palette/gruvbox/magenta     "#cc241d") ; red
(defconst palette/gruvbox/violet      "#d3869b") ; bright-purple
(defconst palette/gruvbox/orange      "#fe8019") ; bright-orange
(defconst palette/gruvbox/yellow      "#fabd2f") ; bright-yellow
(defconst palette/gruvbox/dark-yellow "#d79921") ; yellow
(defconst palette/gruvbox/teal        "#8ec07c") ; bright-aqua
(defconst palette/gruvbox/green       "#b8bb26") ; bright-green
(defconst palette/gruvbox/dark-green  "#98971a") ; green
(defconst palette/gruvbox/blue        "#83a598") ; bright-blue
(defconst palette/gruvbox/dark-blue   "#458588") ; blue
(defconst palette/gruvbox/cyan        "#8ec07c") ; bright-aqua
(defconst palette/gruvbox/my-black    "#37302f")
(defconst palette/gruvbox/dark-cyan   "#689d6a") ; aqua
